# CodeRabbit configuration
# Goal: reduce noisy line comments on docs and legacy content; prefer summaries
version: 1
reviews:
  # Cap the number of line comments to keep PRs readable
  max_comments: 50
  # Prefer a single structured summary with actionable sections
  summary: true
  # Do not post inline comments for these paths; include only in overall summary
  no_inline_comment_paths:
    - "docs/**"
    - ".legacy/**"
    - "**/*.md"
  # Only block on code; never block on docs
  non_blocking_paths:
    - "docs/**"
    - ".legacy/**"
    - "**/*.md"
  # Ignore vendored or generated directories (if present)
  ignore_paths:
    - "build/**"
    - "dist/**"
    - "node_modules/**"
  # Keep suggestions concise
  suggestion_limit: 5
  # Avoid repeating the same comment across files
  deduplicate_comments: true
  # Increase processing timeout for large PRs
  timeout_ms: 300000
