# Requires clang-tidy 20.x - see docs/DEV_SETUP.md
repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v18.1.8
  hooks:
    - id: clang-format
- repo: local
  hooks:
    - id: iwyu
      name: include-what-you-use
      entry: iwyu_tool -p .
      language: system
      files: \.(c|h)$
      exclude: ^core/
      pass_filenames: false
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.4.0
  hooks:
    - id: detect-secrets