# Requires clang-tidy 20.x - see docs/DEV_SETUP.md
repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v18.1.8
  hooks:
    - id: clang-format
- repo: local
  hooks:
    - id: iwyu
      name: include-what-you-use
      entry: >
        bash -c '
          meson setup build >/dev/null 2>&1 || true &&
          ninja -C build >/dev/null 2>&1 || true &&
          echo "IWYU check skipped - requires manual run with proper SDK paths"'
      language: system
      files: \.(c|h)$
      pass_filenames: false
    - id: docs-link-check
      name: docs: link check
      entry: python3 tools/docs/check_docs.py --mode link
      language: python
      files: ^docs/.*\.md$
    - id: docs-toc-check
      name: docs: TOC check
      entry: python3 tools/docs/check_docs.py --mode toc
      language: python
      files: ^docs/.*\.md$
    - id: docs-frontmatter-check
      name: docs: frontmatter check
      entry: python3 tools/docs/check_frontmatter.py
      language: python
      files: ^docs/.*\.md$
    - id: curate-agents
      name: curate AGENTS.md recent developments
      entry: python3 tools/agents/curate_recent.py
      language: python
      files: ^AGENTS\.md$
    - id: one-thing
      name: policy: one-thing (1 file = 1 thing)
      entry: python3 tools/quality/check_one_thing.py
      language: python
      pass_filenames: false
      files: ^(include/|core/include/|core/src/).*(\.(c|h))$
    - id: enforce-public-includes
      name: enforce public includes (no core/src)
      entry: bash tools/enforce-public-includes.sh
      language: system
      pass_filenames: false
    - id: features-update
      name: features ledger update
      entry: python3 scripts/update_progress.py
      language: python
      files: ^docs/features/Features_Ledger\.md$
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.4.0
  hooks:
    - id: detect-secrets
      args: ['--baseline', '.secrets.baseline']

- repo: https://github.com/igorshubovych/markdownlint-cli2
  rev: v0.15.0
  hooks:
    # Auto-fix simple issues first (whitespace, list markers, emphasis style)
    - id: markdownlint-cli2-fix
      name: markdownlint (fix)
      files: \.(md|mdx)$
    # Then lint to catch anything left
    - id: markdownlint-cli2
      name: markdownlint
      files: \.(md|mdx)$
