# Requires clang-tidy 20.x - see docs/DEV_SETUP.md
repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v18.1.8
  hooks:
    - id: clang-format
- repo: local
  hooks:
    - id: iwyu
      name: include-what-you-use
      entry: >
        bash -c '
          meson setup build >/dev/null 2>&1 || true &&
          ninja -C build >/dev/null 2>&1 || true &&
          echo "IWYU check skipped - requires manual run with proper SDK paths"'
      language: system
      files: \.(c|h)$
      pass_filenames: false
    - id: docs-link-check
      name: docs: link check
      entry: python3 tools/docs/check_docs.py --mode link
      language: python
      files: ^docs/.*\.md$
    - id: docs-toc-check
      name: docs: TOC check
      entry: python3 tools/docs/check_docs.py --mode toc
      language: python
      files: ^docs/.*\.md$
    - id: enforce-public-includes
      name: enforce public includes (no core/src)
      entry: bash tools/enforce-public-includes.sh
      language: system
      pass_filenames: false
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.4.0
  hooks:
    - id: detect-secrets
      args: ['--baseline', '.secrets.baseline']
