name: 'git-mind Suggest'
description: 'Run git-mind suggest on a PR and post results as a comment'

inputs:
  agent:
    description: 'Agent command for generating suggestions (overrides GITMIND_AGENT)'
    required: false
  github-token:
    description: 'GitHub token for posting comments'
    required: false
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      shell: bash
      run: npm ci
      working-directory: ${{ github.action_path }}

    - name: Run git-mind suggest
      id: suggest
      shell: bash
      env:
        GITMIND_AGENT: ${{ inputs.agent }}
      run: |
        BASE_SHA="${{ github.event.pull_request.base.sha }}"
        HEAD_SHA="${{ github.event.pull_request.head.sha }}"
        RESULT=$(node ${{ github.action_path }}/bin/git-mind.js suggest --json --context "${BASE_SHA}..${HEAD_SHA}" 2>/dev/null) || true
        echo "result<<GITMIND_EOF" >> "$GITHUB_OUTPUT"
        echo "$RESULT" >> "$GITHUB_OUTPUT"
        echo "GITMIND_EOF" >> "$GITHUB_OUTPUT"

    - name: Post comment
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SUGGEST_RESULT: ${{ steps.suggest.outputs.result }}
      run: |
        node ${{ github.action_path }}/action/post-comment.js \
          "${{ github.repository }}" \
          "${{ github.event.pull_request.number }}"
