# SPDX-License-Identifier: Apache-2.0

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - TERM=xterm-256color
      - DOCKER_BUILD=1
    command: /bin/bash