# SPDX-License-Identifier: Apache-2.0

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
    command: bash
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color

  test:
    build:
      context: ./c
      dockerfile: Dockerfile.test
    volumes:
      - ./c:/test
    working_dir: /test
    command: ./test.sh
    
  benchmark:
    build:
      context: ./c
      dockerfile: Dockerfile.test
    volumes:
      - ./c:/test
    working_dir: /test
    command: ./benchmark.sh