# SPDX-License-Identifier: Apache-2.0
version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace
      - go-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    working_dir: /workspace
    environment:
      - CGO_ENABLED=0
    stdin_open: true
    tty: true

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace:ro
    working_dir: /workspace
    environment:
      - CGO_ENABLED=0
    command: ["sh", "-c", "cd go && go test -v ./..."]

volumes:
  go-cache:
  go-build-cache: