version: '3.8'

services:
  gitmind-test:
    build:
      context: .
      dockerfile: Dockerfile.testenv
    container_name: gitmind-test-env
    volumes:
      # Mount for persistence (optional - comment out for ephemeral testing)
      # - ./test-data:/home/gitmind/git-knowledge-test
      
      # Mount scripts for live updates during development
      - ./scripts:/app/scripts:ro
    
    # Override command to keep container running
    command: /bin/bash -c "cd git-knowledge-test && tail -f /dev/null"
    
    # For interactive testing
    stdin_open: true
    tty: true

  # Chaos worker service (runs chaos-worker.sh continuously)
  chaos-worker:
    build:
      context: .
      dockerfile: Dockerfile.testenv
    container_name: gitmind-chaos-worker
    volumes:
      - ./scripts:/app/scripts:ro
    depends_on:
      - gitmind-test
    # Runs the chaos worker script
    command: /bin/bash -c "cd git-knowledge-test && ./chaos-worker.sh"