name: C-Core Gate
on: [pull_request]
permissions:
  contents: read
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build & capture compile DB
        run: |
          sudo apt-get update && sudo apt-get install -y bear clang make libsodium-dev
          cd core
          make clean || true
          bear -- make all
          mv compile_commands.json ../
      - name: clang-tidy (diff-guard)
        run: |
          clang-tidy -quiet -p . $(git ls-files 'core/**/*.c' 'core/**/*.h') \
            | tee clang-tidy-report-full.txt || true
          # Filter to just project warnings
          grep -E "^/.*core/|^core/" clang-tidy-report-full.txt > clang-tidy-report.txt || true
      - name: Enforce no new warnings
        run: bash tools/enforce_no_new_warnings.sh clang-tidy-report.txt tools/baseline.txt
      - run: cppcheck --enable=all --inconclusive --quiet src
      - run: python tools/run_fuzz.py 60