name: C-Core Gate
on: [pull_request]
permissions:
  contents: read
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM 20 and build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg lsb-release python3-pip
          wget -O - https://apt.llvm.org/llvm.sh | sudo bash -s -- 20
          sudo apt-get install -y clang-20 clang-tidy-20 cppcheck libsodium-dev libgit2-dev libroaring-dev
          sudo ln -sf /usr/bin/clang-tidy-20 /usr/local/bin/clang-tidy
          sudo ln -sf /usr/bin/clang++-20    /usr/local/bin/clang++
          sudo ln -sf /usr/bin/clang-20      /usr/local/bin/clang
          pip3 install --break-system-packages meson ninja
      - name: Build & capture compile DB
        run: |
          CC=clang meson setup build
          ninja -C build
          cp build/compile_commands.json .
      - name: clang-tidy (diff-guard)
        run: |
          clang-tidy -quiet -p . --config-file=quality/.clang-tidy \
            $(git ls-files 'core/**/*.c' 'core/**/*.h' | grep -v -E '(test_|_test\.|/tests/|core/src/hooks/)') \
            | tee clang-tidy-report-full.txt || true
          # Filter to just project warnings
          grep -E "^/.*core/|^core/" clang-tidy-report-full.txt > clang-tidy-report.txt || true
      - name: Enforce no new warnings
        run: python3 tools/count_warnings.py check clang-tidy-report.txt tools/baseline_count.txt
      - name: Build CI Docker image for E2E (parity)
        run: |
          bash ./tools/dev-shell.sh -c true >/dev/null 2>&1 || true
      - name: Run E2E tests inside CI Docker image
        run: |
          IMAGE=${GITMIND_CI_IMAGE:-gitmind/ci:clang-20}
          docker run --rm --label com.gitmind.project=git-mind \
            -v "$PWD":/workspace -w /workspace -e GITMIND_DOCKER=1 "$IMAGE" bash -lc '
              set -e
              CC=clang meson setup build >/dev/null 2>&1 || true
              ninja -C build git-mind
              export GIT_MIND=/workspace/build/git-mind
              rm -rf /tmp/gm-e2e && mkdir -p /tmp/gm-e2e
              cp -r tests/e2e /tmp/gm-e2e/
              cd /tmp/gm-e2e/e2e
              bash ./run_all_tests.sh
            '
      - run: cppcheck --enable=all --inconclusive --quiet apps/cli || true
      - run: python tools/run_fuzz.py 60 || true
