# SPDX-License-Identifier: LicenseRef-MIND-UCAL-1.0
name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  migration-notice:
    runs-on: ubuntu-latest
    
    steps:
    - name: Release Status
      run: |
        echo "🚧 RELEASES DISABLED DURING MIGRATION 🚧"
        echo ""
        echo "No releases until migration complete"
        echo "See docs/enforcer/ROADMAP_TO_REFACTORING.md"
        echo ""
        echo "✅ RELEASE WORKFLOW PASSES (migration mode)"