name: Seed Review Doc (manual)
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      pr:
        description: PR number to seed
        required: true
        type: number

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run seeding script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 tools/review/seed_feedback_from_github.py \
            --owner ${GITHUB_REPOSITORY%%/*} --repo ${GITHUB_REPOSITORY##*/} --pr ${{ inputs.pr }} --out review-seed
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: review-seed
          path: review-seed/**
